(* Fresh full-D momentum tensor check of the specified HF operator continuation.
   Producing-source reuse enumerated before adaptation in provenance/hf/ANGULAR_REUSE_PLAN.json. *)
Clear[RUHFFullDCut];
RUHFFullDCut[generated_Association,cutPolarization_:"physical",rayDamping_:0]:=Module[
 {parent,density,pol,transverse,sp,intpol,vertex3,ka,kb,kc,opena,openb,openc,manualVertex,vertexResidual},
 FCClearScalarProducts[];
 SP[n]=0;SP[p]=0;SP[n,p]=1;SP[e]=-1;SP[e,n]=0;SP[e,p]=0;
 SPD[n]=0;SPD[p]=0;SPD[n,p]=1;
 SP[k,n]=1;SP[k,p]=kt2/(2(1-u));SP[k,e]=-Sqrt[kt2(1-tHat)];SP[k]=kt2 u/(1-u)+tHat kt2;
 SP[l,n]=1-u;SP[l,p]=kt2/(2(1-u));SP[l,e]=-Sqrt[kt2(1-tHat)];SP[l]=tHat kt2;
 SP[k,l]=kt2 u/(2(1-u))+tHat kt2;
 SPD[k,n]=1;SPD[k,p]=kt2/(2(1-u));SPD[k]=kt2 u/(1-u);
 SPD[l,n]=1-u;SPD[l,p]=kt2/(2(1-u));SPD[l]=0;SPD[k,l]=kt2 u/(2(1-u));
 parent=I GS[e].GS[n];density=I GA[al].GS[p];
 pol=If[cutPolarization==="ward",FVD[l,mu]FVD[l,nu],
  -MTD[mu,nu]+(FVD[l,mu]FV[n,nu]+FV[n,mu]FVD[l,nu])/(1-u)];
 transverse=-MT[al,be]+FV[n,al]FV[p,be]+FV[p,al]FV[n,be];
 sp=GS[n]/(2u);
 intpol=-MTD[rho,si]+((FVD[l,rho]+u(1-v)FV[p,rho])FV[n,si]+FV[n,rho](FVD[l,si]+u(1-v)FV[p,si]))/(1-u v-I rayDamping);
 (* All outgoing vertex momenta (-l-g,l,g), g=u(1-v)p. This is the
    actual Lorentz polynomial generated by FeynArts above. *)
 manualVertex=MTD[si,mu](-2FVD[l,be]-u(1-v)FV[p,be])+MTD[mu,be](FVD[l,si]-u(1-v)FV[p,si])+MTD[be,si](FVD[l,mu]+2u(1-v)FV[p,mu]);
 vertex3=(generated["triple_lorentz_polynomial"]/.{Lor1->mu,Lor2->be,Lor4->si})/.
  Pair[aa_LorentzIndex,Momentum[q_,D]]:>(Coefficient[q,l]Pair[aa,Momentum[l,D]]+Coefficient[q,g]u(1-v)Pair[aa,Momentum[p]]);
 vertexResidual=Expand[vertex3-FCI[manualVertex]];
 If[vertexResidual=!=0,Print["FAIL: generated triple vertex routing mismatch: ",InputForm[vertexResidual]];Exit[1]];
 opena=DiracTrace[parent.GSD[k].GAD[nu].density.GA[be].sp.GAD[mu].GSD[k]]pol transverse;
 openb=DiracTrace[parent.GSD[k].GAD[nu].density.GAD[mu].(GSD[k]-u(1-v)GS[p]).GA[be].GSD[k]]pol transverse;
 openc=DiracTrace[parent.GSD[k].GAD[nu].density.GAD[rho].GSD[k]]pol intpol vertex3 transverse;
 ka=Factor[Contract[DiracSimplify[opena,DiracTraceEvaluate->True]]];
 kb=Factor[Contract[DiracSimplify[openb,DiracTraceEvaluate->True]]/(kt2 u(v+I rayDamping)/(1-u))];
 kc=Factor[Contract[DiracSimplify[openc,DiracTraceEvaluate->True]]/(kt2 u(1-v+I rayDamping)/(1-u))];
 <|"status"->"DERIVED_FULL_D_MOMENTUM_HF_CUT_FOR_ANGULAR_CHECK",
 "spin_prescription"->"BMHV physical external tensor and transverse coherent index; D-dimensional emitted/internal gluon metric; D=4-2eps only after contraction.",
 "polarization_kind"->cutPolarization,"physical_projector"->parent,"HF_projector"->density,
 "ray_damping"->rayDamping,
 "regulated_denominator_origin"->"A single positive dimensionless damping parameter is used. Future Fourier rays give qplus-i lambda; internal Feynman denominators give virtuality+i lambda times their positive scale kt2*u/(1-u). This scaling retains the same i0 distribution on the physical branch. The complete Hermitian action retains the conjugate prescription. Physical endpoint limits and the order of removing damping must be established separately.",
 "cut_polarization"->pol,"coherent_transverse_projector"->transverse,
 "internal_axial_polarization"->intpol,"triple_gluon_vertex"->vertex3,"generated_vertex_routing_residual"->vertexResidual,
 "special_propagator"->sp,
 "special_propagator_origin"->"slash(u p+rho n)/(2u rho)=slash(p)/(2rho)+slash(n)/(2u). D17GaugeCompletion separately retains the leading term, proves its transverse F-density contraction zero, and establishes the full covariant/Wilson current reduction to these axial graphs.",
 "open_traces"-><|"a"->opena,"b"->openb,"c"->openc|>,
 "D_traces"-><|"a"->ka,"b"->kb,"c"->kc|>,
 "epsilon0"->Map[Factor[#/.D->4]&,<|"a"->ka,"b"->kb,"c"->kc|>],
 "epsilon1"->Map[Factor[SeriesCoefficient[#/.D->4-2eps,{eps,0,1}]]&,<|"a"->ka,"b"->kb,"c"->kc|>],
 "kinematics"->HoldComplete[{kBar==p+kt2 n/(2(1-u))+Sqrt[kt2(1-tHat)]e,kHat^2==-tHat kt2,k==kBar+kHat,l==k-u p,r1==u v p,g==u(1-v)p}],
 "cut_jacobian"->1/(2(1-u)),"common_parent_propagators"->(1-u)^2/(kt2^2 u^2),
 "domain"->HoldComplete[0<u<1&&0<v<1&&kt2>0],
 "limitations"->{"The ordered physical support and operator map are actual d16 dependencies, not proved by this trace alone.","The complete open Wilson current and regulated action are separate d17 outputs.","Global normalization is supplied by d16 and the explicit conjugate-cut calculation."}|>
];

Clear[RUHFAngularProof];
RUHFAngularProof[generated_Association,nominalDensity_,normalization_Association]:=Module[
 {full,tr,col,raw,weight,form,coeffs,rankMellin,scalarMellin,commonContinuation,
 weightedMoments,ratios,canonical,difference,finiteDifference,checks},
 full=RUHFFullDCut[generated];
 tr=full["D_traces"]/.Pair[Momentum[k,D-4],Momentum[k,D-4]]->-tHat kt2;
 col=CF tr["a"]+(CF-CA/2)tr["b"]-CA tr["c"]/2;
 raw=2(Times@@Values[normalization])Sqrt[1-tHat]col/(1-v);
 (* Positive-radical assumptions are essential. PowerExpand would discard
    this branch information and is deliberately not used. *)
 weight=Factor[FullSimplify[raw,kt2>0&&0<tHat<1&&0<u<1&&0<v<1]/.D->4-2eps];
 RUHFGate["HF full-D hats substituted before epsilon expansion",FreeQ[weight,_Pair|_Momentum]];
 RUHFGate["HF full-D zero-hat limit",Factor[(weight/.tHat->0)-nominalDensity]===0];
 form=Factor[weight/(1-tHat)];
 RUHFGate["HF full-D angular tensor polynomial",PolynomialQ[form,tHat]];
 coeffs=CoefficientList[form,tHat];
 (* The physical rank-one phase depends on tau*(1-tHat). The radial
    integration therefore supplies (1-tHat)^eps before the hat-fraction
    integral. Averaging the tensor and then substituting J0 is not valid. *)
 rankMellin=Integrate[tauH^(-1-eps)BesselJ[1,2Sqrt[AA tauH]]/Sqrt[AA tauH],
   {tauH,0,Infinity},Assumptions->AA>0&&-1/4<eps<0];
 scalarMellin=Integrate[tauH^(-1-eps)BesselJ[0,2Sqrt[AA tauH]],
   {tauH,0,Infinity},Assumptions->AA>0&&-1/4<eps<0];
 commonContinuation=1/(Gamma[1-eps]Gamma[1+eps]);
 weightedMoments=Table[(-eps)Integrate[tHat^(j-1-eps)(1-tHat)^(1+eps),
   {tHat,0,1},Assumptions->-1<eps<0],{j,0,Length[coeffs]-1}];
 ratios=FullSimplify[FunctionExpand[(rankMellin/scalarMellin)commonContinuation #]&/@weightedMoments,
   -1<eps<0&&AA>0];
 canonical=Factor[coeffs.ratios];difference=Factor[canonical-nominalDensity];
 finiteDifference=Factor[Coefficient[Normal[Series[difference scalarMellin/.AA->1,{eps,0,0}]],eps,0]];
 checks=<|"hat_zero"->Factor[(weight/.tHat->0)-nominalDensity],
  "rank_scalar_Mellin_ratio"->FullSimplify[FunctionExpand[rankMellin/scalarMellin]-1/(1+eps),AA>0&&-1/4<eps<0],
  "leading_tensor_transport"->Factor[First[ratios]-1],
  "epsilon0"->Factor[SeriesCoefficient[difference,{eps,0,0}]],
  "epsilon1"->Factor[SeriesCoefficient[difference,{eps,0,1}]],"finite_radial_difference"->finiteDifference|>;
 RUHFGate["HF independent full-D angular finite-order equivalence",RUHFZeroQ[Values[checks]]];
 <|"status"->"EXACT_ZERO_ONE_LOOP_FINITE_DIFFERENCE_IN_DECLARED_OPERATOR_CONTINUATION",
  "full_D_native_cut"->full,"physical_hat_fraction"->HoldComplete[rhoHat==tHat tau&&rhoPhysical==(1-tHat)tau],
  "rank_weight"->weight,"tensor_coefficient_polynomial"->form,"tensor_coefficients"->coeffs,
  "actual_rank_one_Mellin"->rankMellin,"actual_scalar_Mellin"->scalarMellin,
  "rank_phase"->HoldComplete[BesselJ[1,2Sqrt[AA tauH(1-tHat)]]/Sqrt[AA tauH(1-tHat)]],
  "weighted_Beta_moments"->weightedMoments,"common_operator_continuation"->commonContinuation,
  "ratios_to_nominal_J0_per_tensor_power"->ratios,"full_D_canonical_density"->canonical,
  "nominal_physical_plane_density"->nominalDensity,"all_epsilon_density_difference"->difference,"checks"->checks,
  "scope"->"Full-D parent/emitted momenta with physical external tensor and coherent index. The physical rank-one phase is integrated before hat-angle averaging and the declared common b-independent scalar/rank-one operator continuation acts after full-D Fourier integration. Equality is only through one-loop finite order: the calculated difference begins at eps^2 and HF has one radial pole on the uniform physical endpoint class. No all-epsilon or generic endpoint-contact equality."|>
];
