(* v0.5.1 fresh HF generating source; exact pre-use identity in provenance/hf/COLLINS_REUSE_PLAN.json. No archived output or radial library is loaded. *)
(* Additive d17 implementation. This file reads no reference coefficient.
   It constructs the coherent-gluon cut numerator, with physical external
   chiral-odd indices and D-dimensional internal gluons. The gauge-complete
   operator endpoint and normalization are NOT certified by these traces. *)
Clear[D17GeneratedGraphs,D17PrimaryCut,D17IndependentCut];
D17GeneratedGraphs[]:=Module[{graphs,fa,fc,colA,colB,triple},
 graphs=InsertFields[CreateTopologies[0,1->3],{F[3,{1}]}->{F[3,{1}],V[5],V[5]},Model->"SMQCD",InsertionLevel->{Particles},ExcludeParticles->{V[1|2|3],S[_],U[_]}];
 fa=CreateFeynAmp[graphs,PreFactor->1];
 fc=FCFAConvert[fa,IncomingMomenta->{k},OutgoingMomenta->{r1,l,g},UndoChiralSplittings->True,ChangeDimension->D,List->True,SMP->True,Contract->False,DropSumOver->True,FinalSubstitutions->{SMP["m_u"]->0}];
 colA=SUNSimplify[SUNT[ca,ca,cb]];colB=SUNSimplify[SUNT[ca,cb,ca]];
 triple=Cases[fc[[1]],x_Plus/;!FreeQ[x,Pair]&&FreeQ[x,SMP]:>x,Infinity];
 If[Length[triple]=!=1,Print["FAIL: generated three-gluon vertex extraction"];Exit[1]];
 <|"graphs"->graphs,"FeynArts"->fa,"FeynCalc"->fc,"graph_count"->Length[fa],
   "color_a"->colA,"color_b"->colB,"triple_lorentz_polynomial"->First[triple],
   "scope"->"Generated q to qgg tree skeletons. Their collinear special propagator and Wilson/EOM completion are separate operator operations; tree graph generation alone does not certify those operations."|>
];
D17PrimaryCut[generated_Association,cutPolarization_:"physical",rayDamping_:0]:=Module[
 {parent,density,pol,transverse,sp,intpol,vertex3,ka,kb,kc,opena,openb,openc,manualVertex,vertexResidual},
 FCClearScalarProducts[];
 SP[n]=0;SP[p]=0;SP[n,p]=1;SP[e]=-1;SP[e,n]=0;SP[e,p]=0;
 SP[k,n]=1;SP[k,p]=kt2/(2(1-u));SP[k,e]=-Sqrt[kt2];SP[k]=kt2 u/(1-u);
 SP[l,n]=1-u;SP[l,p]=kt2/(2(1-u));SP[l,e]=-Sqrt[kt2];SP[l]=0;
 SP[k,l]=kt2 u/(2(1-u));
 parent=I GS[e].GS[n];density=I GA[al].GS[p];
 pol=If[cutPolarization==="ward",FV[l,mu]FV[l,nu],
  -MTD[mu,nu]+(FV[l,mu]FV[n,nu]+FV[n,mu]FV[l,nu])/(1-u)];
 transverse=-MT[al,be]+FV[n,al]FV[p,be]+FV[p,al]FV[n,be];
 sp=GS[n]/(2u);
 intpol=-MTD[rho,si]+((FV[l,rho]+u(1-v)FV[p,rho])FV[n,si]+FV[n,rho](FV[l,si]+u(1-v)FV[p,si]))/(1-u v-I rayDamping);
 (* All outgoing vertex momenta (-l-g,l,g), g=u(1-v)p. This is the
    actual Lorentz polynomial generated by FeynArts above. *)
 manualVertex=MTD[si,mu](-2FV[l,be]-u(1-v)FV[p,be])+MTD[mu,be](FV[l,si]-u(1-v)FV[p,si])+MTD[be,si](FV[l,mu]+2u(1-v)FV[p,mu]);
 vertex3=(generated["triple_lorentz_polynomial"]/.{Lor1->mu,Lor2->be,Lor4->si})/.
  Pair[aa_LorentzIndex,Momentum[q_,D]]:>(Coefficient[q,l]Pair[aa,Momentum[l]]+Coefficient[q,g]u(1-v)Pair[aa,Momentum[p]]);
 vertexResidual=Expand[vertex3-FCI[manualVertex]];
 If[vertexResidual=!=0,Print["FAIL: generated triple vertex routing mismatch: ",InputForm[vertexResidual]];Exit[1]];
 opena=DiracTrace[parent.GS[k].GAD[nu].density.GA[be].sp.GAD[mu].GS[k]]pol transverse;
 openb=DiracTrace[parent.GS[k].GAD[nu].density.GAD[mu].(GS[k]-u(1-v)GS[p]).GA[be].GS[k]]pol transverse;
 openc=DiracTrace[parent.GS[k].GAD[nu].density.GAD[rho].GS[k]]pol intpol vertex3 transverse;
 ka=Factor[Contract[DiracSimplify[opena,DiracTraceEvaluate->True]]];
 kb=Factor[Contract[DiracSimplify[openb,DiracTraceEvaluate->True]]/(kt2 u(v+I rayDamping)/(1-u))];
 kc=Factor[Contract[DiracSimplify[openc,DiracTraceEvaluate->True]]/(kt2 u(1-v+I rayDamping)/(1-u))];
 <|"status"->"DERIVED_AXIAL_CUT_NUMERATORS",
 "spin_prescription"->"BMHV physical external tensor and transverse coherent index; D-dimensional emitted/internal gluon metric; D=4-2eps only after contraction.",
 "polarization_kind"->cutPolarization,"physical_projector"->parent,"HF_projector"->density,
 "ray_damping"->rayDamping,
 "regulated_denominator_origin"->"A single positive dimensionless damping parameter is used. Future Fourier rays give qplus-i lambda; internal Feynman denominators give virtuality+i lambda times their positive scale kt2*u/(1-u). This scaling retains the same i0 distribution on the physical branch. The complete Hermitian action retains the conjugate prescription. Physical endpoint limits and the order of removing damping must be established separately.",
 "cut_polarization"->pol,"coherent_transverse_projector"->transverse,
 "internal_axial_polarization"->intpol,"triple_gluon_vertex"->vertex3,"generated_vertex_routing_residual"->vertexResidual,
 "special_propagator"->sp,
 "special_propagator_origin"->"slash(u p+rho n)/(2u rho)=slash(p)/(2rho)+slash(n)/(2u). D17GaugeCompletion separately retains the leading term, proves its transverse F-density contraction zero, and establishes the full covariant/Wilson current reduction to these axial graphs.",
 "open_traces"-><|"a"->opena,"b"->openb,"c"->openc|>,
 "D_traces"-><|"a"->ka,"b"->kb,"c"->kc|>,
 "epsilon0"->Map[Factor[#/.D->4]&,<|"a"->ka,"b"->kb,"c"->kc|>],
 "epsilon1"->Map[Factor[SeriesCoefficient[#/.D->4-2eps,{eps,0,1}]]&,<|"a"->ka,"b"->kb,"c"->kc|>],
 "kinematics"->HoldComplete[k==p+kt2 n/(2(1-u))+Sqrt[kt2]e,l==k-u p,r1==u v p,g==u(1-v)p],
 "cut_jacobian"->1/(2(1-u)),"common_parent_propagators"->(1-u)^2/(kt2^2 u^2),
 "domain"->HoldComplete[0<u<1&&0<v<1&&kt2>0],
 "limitations"->{"The ordered physical support and operator map are actual d16 dependencies, not proved by this trace alone.","The complete open Wilson current and regulated action are separate d17 outputs.","Global normalization is supplied by d16 and the explicit conjugate-cut calculation."}|>
];
D17IndependentCut[]:=Module[
 {gm,mt,sl,dp,np,nm,ex,ey,kv,lv,gv,k1v,iv,pol,ipol,parent,special,
  a4,b4,c4,ahat,bhat,chat,den,vv,res,am,bm,cm,amh,bmh,cmh,mirror},
 gm=PhysicalGammas[];mt={1,-1,-1,-1};sl[x_]:=PhysicalSlash[x,gm];dp[x_,y_]:=MDot[x,y];
 np={1,0,0,1}/Sqrt[2];nm={1,0,0,-1}/Sqrt[2];ex={0,1,0,0};ey={0,0,1,0};
 kv=np+kt2/(2(1-u))nm+Sqrt[kt2]ex;lv=kv-u np;gv=u(1-v)np;k1v=kv-gv;iv=lv+gv;
 pol=Table[-mt[[mu]]KroneckerDelta[mu,nu]+mt[[mu]]mt[[nu]](lv[[mu]]nm[[nu]]+nm[[mu]]lv[[nu]])/(1-u),{mu,4},{nu,4}];
 ipol=Table[-mt[[rho]]KroneckerDelta[rho,si]+mt[[rho]]mt[[si]](iv[[rho]]nm[[si]]+nm[[rho]]iv[[si]])/(1-u v),{rho,4},{si,4}];
 parent=I sl[ex].sl[nm];special=sl[nm]/(2u);
 a4=0;b4=0;c4=0;ahat=0;bhat=0;chat=0;
 am=0;bm=0;cm=0;amh=0;bmh=0;cmh=0;
 Do[den=I sl[ea].sl[np];
  a4+=Sum[pol[[mu,nu]]Tr[parent.sl[kv].gm[[nu]].den.sl[ea].special.gm[[mu]].sl[kv]],{mu,4},{nu,4}];
  b4+=Sum[pol[[mu,nu]]Tr[parent.sl[kv].gm[[nu]].den.gm[[mu]].sl[k1v].sl[ea].sl[kv]],{mu,4},{nu,4}]/dp[k1v,k1v];
  (* The right-cut contribution is formed from the reversed Dirac-bar
     chain before evaluating a trace. All slash blocks, parent and physical
     density are Dirac-Hermitian; real cut polarizations remain unchanged.
     This is a second cut placement, not an extra averaging of the density. *)
  am+=Sum[pol[[mu,nu]]Tr[parent.sl[kv].gm[[mu]].special.sl[ea].den.gm[[nu]].sl[kv]],{mu,4},{nu,4}];
  bm+=Sum[pol[[mu,nu]]Tr[parent.sl[kv].sl[ea].sl[k1v].gm[[mu]].den.gm[[nu]].sl[kv]],{mu,4},{nu,4}]/dp[k1v,k1v];
  (* Each pair of contracted hat gammas crosses respectively 4 and 2
     physical gammas. The spacelike metric supplies the displayed signs. *)
  ahat+=-Tr[parent.sl[kv].den.sl[ea].special.sl[kv]];
  bhat+=-Tr[parent.sl[kv].den.sl[k1v].sl[ea].sl[kv]]/dp[k1v,k1v];
  amh+=-Tr[parent.sl[kv].special.sl[ea].den.sl[kv]];
  bmh+=-Tr[parent.sl[kv].sl[ea].sl[k1v].den.sl[kv]]/dp[k1v,k1v];
  vv=Table[mt[[si]]KroneckerDelta[si,mu]dp[-2lv-gv,ea]+ea[[mu]](lv-gv)[[si]]+ea[[si]](lv+2gv)[[mu]],{si,4},{mu,4}];
  c4+=Sum[pol[[mu,nu]]ipol[[rho,si]]vv[[si,mu]]Tr[parent.sl[kv].gm[[nu]].den.gm[[rho]].sl[kv]],{mu,4},{nu,4},{rho,4},{si,4}]/dp[iv,iv];
  cm+=Sum[pol[[mu,nu]]ipol[[rho,si]]vv[[si,mu]]Tr[parent.sl[kv].gm[[rho]].den.gm[[nu]].sl[kv]],{mu,4},{nu,4},{rho,4},{si,4}]/dp[iv,iv];
  (* Only the metric connecting the internal and emitted hat indices
     survives. Both axial momenta and the coherent polarization are physical. *)
  chat+=dp[-2lv-gv,ea]Tr[parent.sl[kv].den.sl[kv]]/dp[iv,iv];
  cmh+=dp[-2lv-gv,ea]Tr[parent.sl[kv].den.sl[kv]]/dp[iv,iv],{ea,{ex,ey}}];
 res=<|"a"->Factor[a4+(D-4)ahat],"b"->Factor[b4+(D-4)bhat],"c"->Factor[c4+(D-4)chat]|>;
 mirror=<|"a"->Factor[am+(D-4)amh],"b"->Factor[bm+(D-4)bmh],"c"->Factor[cm+(D-4)cmh]|>;
 <|"origin"->"Independent explicit Clifford-matrix contractions plus hat-space algebra; no FeynCalc trace result or primary finite export is an input.",
  "D_traces"->res,"physical_traces"->Map[Factor,<|"a"->a4,"b"->b4,"c"->c4|>],
  "conjugate_cut_D_traces"->mirror,
  "conjugate_cut_residuals"->AssociationMap[Factor[mirror[#]-res[#]]&,{"a","b","c"}],
  "conjugate_cut_scope"->"Each single-cut chain is reversed with its Dirac bar before contraction; the imaginary physical HF scalar is real after its defining projector. The source parent z_h^2/4 is its spin-averaged projected parent after taking the real component, not an extra h.c./2 factor. Two distinct hard cut placements each enter once and sum to twice the unsymmetrized trace. The native parent and inverse density ratios cancel as derived in the actual d16 input.",
  "hat_traces"->Map[Factor,<|"a"->ahat,"b"->bhat,"c"->chat|>],
  "lightfront_residuals"->Factor/@{dp[kv,kv]-kt2 u/(1-u),dp[lv,lv],dp[k1v,k1v]-kt2 u v/(1-u),dp[iv,iv]-kt2 u(1-v)/(1-u)},
  "scope"->"Independent Clifford/hat route for the complete physical axial graph reduction, including O(eps). It shares the separately derived operator normalization, open-current gauge reduction and support assumptions; their validity is not independently proved by the equality of these traces."|>
];
