#!/usr/bin/env python3
"""Real POSIX filesystem/Git regressions for the historical baseline contract.

Expected records are independent of support.sha/baseline_check. The captured
fixture contains all 253 link targets and baseline digests from the supplied
preflight review, rather than expectations generated by the corrected code.
No Wolfram, Kira, SubTropica, fitted input or production computation is used.
"""
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

import support

HERE = Path(__file__).resolve().parent


class HistoricalBaselineTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix='collins-baseline-regression-')
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.repo = self.root / 'repo'
        self.repo.mkdir()
        self.state = self.root / 'state'
        self.state.mkdir()
        self.git('init', '--quiet')
        self.git('config', 'core.filemode', 'true')
        self.git('config', 'core.symlinks', 'true')
        (self.repo / 'original.txt').write_bytes(b'original content\n')
        (self.repo / 'original.txt').chmod(0o644)
        self.git('add', 'original.txt')
        self.records = {'original.txt': {
            'sha256': hashlib.sha256(b'original content\n').hexdigest(),
            'git_mode': '100644', 'is_symlink': False, 'executable': False,
        }}

    def git(self, *args):
        result = subprocess.run(['git', '-C', str(self.repo), *args],
                                capture_output=True, text=True, check=True,
                                env={**os.environ, 'GIT_OPTIONAL_LOCKS': '0'})
        return result.stdout

    def link(self, name, target, digest=None):
        path = self.repo / name
        path.parent.mkdir(parents=True, exist_ok=True)
        os.symlink(target, path)
        self.git('add', '--', name)
        self.records[name] = {
            'sha256': digest or hashlib.sha256(b'symlink\0' + os.fsencode(target)).hexdigest(),
            'git_mode': '120000', 'is_symlink': True,
            'executable': bool(path.lstat().st_mode & 0o111),
        }
        return path

    def seal(self):
        # Fixture creation only. Never run init against the user's baseline.
        self.baseline = self.state / 'baseline.json'
        document = {'schema': 1, 'repo': str(self.repo), 'head': 'fixture-head',
                    'files': self.records, 'origin': '', 'initial_status': ''}
        self.baseline.write_text(json.dumps(document, indent=2, sort_keys=True) + '\n')
        self.before = self.baseline.read_bytes()
        (self.state / 'historical-report.json').write_text('{"preserve": true}\n')

    def check(self):
        result = support.baseline_check(self.repo, self.state)
        self.assertEqual(result['tracked_files'], len(self.records))
        self.assertEqual(result['baseline_sha256'], hashlib.sha256(self.before).hexdigest())
        self.assertEqual(self.baseline.read_bytes(), self.before)
        return result

    def reject(self):
        with self.assertRaisesRegex(ValueError, 'Original tracked files changed'):
            support.baseline_check(self.repo, self.state)
        self.assertEqual(self.baseline.read_bytes(), self.before)

    def test_regular_file_unchanged(self):
        self.seal()
        self.check()

    def test_file_symlink_unchanged(self):
        self.link('file-link', 'original.txt')
        self.seal()
        self.check()

    def test_directory_symlink_unchanged(self):
        (self.repo / 'directory').mkdir()
        self.link('directory-link', 'directory')
        self.seal()
        self.check()

    def test_dangling_symlink_unchanged(self):
        self.link('dangling-link', 'missing.txt')
        self.seal()
        self.check()

    def test_absolute_symlink_unchanged(self):
        self.link('absolute-link', str(self.repo / 'original.txt'))
        self.seal()
        self.check()

    def test_unicode_target_unchanged(self):
        self.link('unicode-link', 'missing-π-é.txt')
        self.seal()
        self.check()

    def test_non_utf8_target_bytes_unchanged(self):
        self.link('byte-link', b'missing-\xff-\xfe.txt')
        self.seal()
        self.check()

    def test_all_253_captured_baseline_digests(self):
        rows = json.loads((HERE / 'fixtures/captured_symlinks.json').read_text())['symlinks']
        self.assertEqual(len(rows), 253)
        self.assertEqual(len({row['path'] for row in rows}), 253)
        for row in rows:
            self.link(row['path'], row['target'], row['baseline_sha256'])
        self.seal()
        self.check()

    def test_retarget_same_content_rejected(self):
        (self.repo / 'copy.txt').write_bytes((self.repo / 'original.txt').read_bytes())
        path = self.link('file-link', 'original.txt')
        self.seal()
        path.unlink()
        path.symlink_to('copy.txt')
        self.reject()

    def test_retarget_equivalent_spelling_rejected(self):
        path = self.link('file-link', 'original.txt')
        self.seal()
        path.unlink()
        path.symlink_to('./original.txt')
        self.reject()

    def test_retarget_directory_rejected(self):
        (self.repo / 'first').mkdir()
        (self.repo / 'second').mkdir()
        path = self.link('directory-link', 'first')
        self.seal()
        path.unlink()
        path.symlink_to('second')
        self.reject()

    def test_retarget_dangling_rejected(self):
        path = self.link('dangling-link', 'missing-first')
        self.seal()
        path.unlink()
        path.symlink_to('missing-second')
        self.reject()

    def test_deleted_symlink_rejected(self):
        path = self.link('file-link', 'original.txt')
        self.seal()
        path.unlink()
        self.reject()

    def test_deleted_dangling_symlink_rejected(self):
        path = self.link('dangling-link', 'missing')
        self.seal()
        path.unlink()
        self.reject()

    def test_symlink_replaced_by_target_text_file_rejected(self):
        path = self.link('file-link', 'original.txt')
        self.seal()
        path.unlink()
        path.write_bytes(b'original.txt')
        self.reject()

    def test_regular_file_replaced_by_same_content_symlink_rejected(self):
        self.seal()
        (self.repo / 'copy.txt').write_bytes(b'original content\n')
        path = self.repo / 'original.txt'
        path.unlink()
        path.symlink_to('copy.txt')
        self.reject()

    def test_modified_regular_file_rejected(self):
        self.seal()
        (self.repo / 'original.txt').write_bytes(b'changed\n')
        self.reject()

    def test_modified_tracked_target_through_link_rejected(self):
        path = self.link('file-link', 'original.txt')
        self.seal()
        path.write_bytes(b'changed through symlink\n')
        self.reject()

    def test_deleted_regular_file_rejected(self):
        self.seal()
        (self.repo / 'original.txt').unlink()
        self.reject()

    def test_executable_bit_change_rejected(self):
        self.seal()
        (self.repo / 'original.txt').chmod(0o755)
        self.reject()

    def test_index_mode_change_rejected(self):
        self.seal()
        self.git('update-index', '--chmod=+x', 'original.txt')
        self.reject()

    def test_untracked_original_link_rejected(self):
        self.link('file-link', 'original.txt')
        self.seal()
        self.git('rm', '--cached', '--quiet', 'file-link')
        self.reject()

    def test_untagged_symlink_baseline_is_not_accepted(self):
        self.link('file-link', 'original.txt')
        self.records['file-link']['sha256'] = hashlib.sha256(b'original.txt').hexdigest()
        self.seal()
        self.reject()

    def test_link_is_not_a_recursive_target_inventory(self):
        (self.root / 'external.txt').write_bytes(b'old')
        self.link('external-link', '../external.txt')
        self.seal()
        (self.root / 'external.txt').write_bytes(b'new')
        self.check()

    def test_additions_are_allowed(self):
        self.seal()
        (self.repo / 'new-source.txt').write_bytes(b'additive implementation')
        self.git('add', 'new-source.txt')
        self.check()

    def test_baseline_and_historical_report_are_read_only(self):
        self.link('file-link', 'original.txt')
        self.seal()
        before = {p.name: p.read_bytes() for p in self.state.iterdir()}
        self.check()
        self.assertEqual(before, {p.name: p.read_bytes() for p in self.state.iterdir()})

    def test_missing_baseline_is_not_initialized(self):
        with self.assertRaises(support.Blocked):
            support.baseline_check(self.repo, self.state)
        self.assertEqual(list(self.state.iterdir()), [])

    def test_wrong_repository_path_rejected(self):
        self.seal()
        with self.assertRaises(support.Blocked):
            support.baseline_check(self.root, self.state)

    def test_generic_artifact_sha_convention_is_unchanged(self):
        path = self.link('file-link', 'original.txt')
        self.assertEqual(support.sha(path), hashlib.sha256(b'original.txt').hexdigest())

    def test_production_artifact_symlinks_still_rejected(self):
        self.link('file-link', 'original.txt')
        with self.assertRaises(ValueError):
            support.relative_file(self.repo, 'file-link')
        with self.assertRaises(ValueError):
            support.snapshot(self.repo)


if __name__ == '__main__':
    unittest.main()
